### ISSUE TITLE
UInt is not tested

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/roast#108]
I'm not sure if that's the right place to report that (why there are no “is not tested” issues here?).

It looks like there are no tests for **UInt**.

**Comment by hchienjo** [comment]
What about https://github.com/perl6/roast/blob/master/S32-num/int.t#L152? Or the tests should go to its own file and more test cases added?

**Comment by zoffixznet** [comment]
There's also one more in that file: https://github.com/perl6/roast/blob/master/S32-num/int.t#L256

**Comment by AlexDaniel** [comment]
Well, yea, I guess it is enough to close this issue.
