### ISSUE TITLE
Tie-breaking rule between where-blocked multi and non-where-blocked multi is not specced

### ISSUE THREAD

**Issue by titsuki** [perl6/roast#154]
I can find the tie-breaking rule between **where-blocked multi** routines in roast.
https://github.com/perl6/roast/blob/master/S06-multi/subsignature.t#L431-L441

However, it seems that there is another tie-breaking rule that **where-blocked multi** has higher priority than **non-where-blocked multi**.

The following example shows the above mentioned rule.
```
$ perl6 -e 'multi foo(Int $a){ say "1st" }; multi foo(Int $a where *.so){ say "2nd" }; foo(-1)'
2nd
```

```
$ perl6 -e 'multi foo(Int $a where *.so){ say "1st" }; multi foo(Int $a){ say "2nd" }; foo(-1)'
1st
```

**Comment by zoffixznet** [comment]
> However, it seems that there is another tie-breaking rule that where-blocked multi has higher priority than non-where-blocked multi.

Yes, and it's part of the test quoted: https://github.com/perl6/roast/blob/master/S06-multi/subsignature.t#L437

it gets called when the argument is `1` and [gives `1` as the result](https://github.com/perl6/roast/blob/master/S06-multi/subsignature.t#L440)

**Comment by titsuki** [comment]
@zoffixznet 
Thanks for your reply !
I understand that, but I think we need another test case that implicitly shows the tie-breaking rule. 
The test case defines a **non-where-blocked multi** routine first and a **where-blocked multi** routine second so that we can confirm Perl 6 call the second one first.

**Comment by zoffixznet** [comment]
> The test case defines a non-where-blocked multi routine first and a where-blocked multi routine second so that we can confirm Perl 6 call the second one first.

Sure. Submit a PR with that test, please.

**Comment by titsuki** [comment]
ok. I've sent a PR.

**Comment by titsuki** [comment]
@zoffixznet 
Thanks for merging my PR !
