### ISSUE TITLE
no tests for sub cross

### ISSUE THREAD

**Issue by gfldex** [perl6/roast#165]
Alias to infix:<X> defined in src/core/List.pm. Likely just an oversight, still at least a test for existence is required.

**Comment by gfldex** [comment]
revert https://github.com/perl6/doc/commit/b101e5e439 to get the docs back in

**Comment by jonathanstowe** [comment]
I've just added 2 tests to check the interface, but the rest of it is covered in the S03-metaops/cross.t so it probably doesn't need more

**Comment by zoffixznet** [comment]
New files need to be added to [`t/spectest.data`](https://github.com/rakudo/rakudo/blob/nom/t/spectest.data). Would you send a PR, please?

**Comment by jonathanstowe** [comment]
Sorry forgot that

**Comment by jonathanstowe** [comment]
See https://github.com/rakudo/rakudo/pull/897 as it is already saying above
