### ISSUE TITLE
indir() appears to be undertested

### ISSUE THREAD

**Issue by zoffixznet** [perl6/roast#204]
We have [indir()](https://github.com/rakudo/rakudo/blob/5023bf39f102697ae52707661a29547ab0938ab2/src/core/io_operators.pm#L177) sub, but it appears to be both untested and undocumented.

**Comment by AlexDaniel** [comment]
One test is great, but I'd say not enough to close the issue.

**Comment by zoffixznet** [comment]
This will be addressed as part of the IO grant.

Could we please delay adding any further tests prior to the routine being fixed/improved.
