### ISSUE TITLE
Add tests for mixed ⁇ ‼ ?? !!

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/roast#248]
Tests for ``⁇ ‼`` were added [in this commit](https://github.com/perl6/roast/commit/b8965869d22f2e24a41aa5c10eef81563cf9d888).

However, none of these tests use ``⁇ ‼`` in a combination with ``?? !!``.

**Comment by zoffixznet** [comment]
The fancy ones were removed; this Issue is no longer relevant.
