### ISSUE TITLE
$*MAIN-ALLOW-NAMED-ANYWHERE works but its not specced

### ISSUE THREAD

**Issue by ufobat** [perl6/roast#274]
my $*MAIN-ALLOW-NAMED-ANYWHERE = True;
allows to use named parameters on the command line wherever you like, but it's not specced

see https://github.com/perl6/doc/pull/1397

**Comment by lizmat** [comment]
> On 29 Jun 2017, at 14:38, Martin Barth <notifications@github.com> wrote:
> 
> my $*MAIN-ALLOW-NAMED-ANYWHERE = True;
> 
> allows to use named parameters on the command line wherever you like, but it's not specced
> 
> see perl6/doc#1397

And perhaps it shouldn’t as it appears to have only been used in panda, and we’re rethinking how to extend MAIN’s functionality atm.



Liz

**Comment by zoffixznet** [comment]
Yeah. I'll take care of it in about 10 hours.
