### ISSUE TITLE
`byte` type isn't tested

### ISSUE THREAD

**Issue by zoffixznet** [perl6/roast#276]
It does not appear `byte` type is tested.

I'm guessing we can add `byte` to @int-types at the top of S02-types/int-uint.t and fix up the rest of the file to handle it, if needed.

The test for a ticket added in https://github.com/perl6/roast/commit/3bc8e6df53 will be subsumed by the rest of the logic in int-uint.t, if `byte` is added to the list.

**Comment by mryan** [comment]
All done.
