### ISSUE TITLE
Mixy.total-positive

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/roast#294]
Commit https://github.com/rakudo/rakudo/commit/f49c49bb5116fc896cad06c8a45aa993e7353e3b introduced Mixy.total-positive but there are no tests.

**Comment by lizmat** [comment]
From my POV, this is intentional, because I’m not sure we want to make this method public.  The only reason it is not a private method is because of the severe performance penalty of having private methods in roles.

**Comment by zoffixznet** [comment]
Perhaps we should rename it to `.RAKUDO-INTERNAL-TOTAL-POSITIVE` until we decide to make it private, if ever?

Knowing our users, they'll otherwise start using it, even if it's not in docs or roast.

**Comment by lizmat** [comment]
Made it a private method, so the issue can be closed.
