### ISSUE TITLE
Broken todo-ed precomp interning test

### ISSUE THREAD

**Issue by zoffixznet** [perl6/roast#391]
https://irclog.perlgeek.de/perl6/2018-02-25#i_15857861

```
pmurias | https://github.com/perl6/roast/blob/master/S10-packages/precompilation.t#L169 - this test is broken as we just don't find the module this way
 (so if the interning works or not is not even tested)
```

The test [loads modules by name](https://github.com/perl6/roast/blob/2c021d7a1b74b897e7fe5f34e0b9cabcf4bd23e3/S10-packages/precompilation.t#L169) but there's [no source file](https://github.com/perl6/roast/blob/2c021d7a1b74b897e7fe5f34e0b9cabcf4bd23e3/S10-packages/precompilation.t#L131) and only  a `$precomp-ext` file.

Is such loading mechanism meant to work?

**Comment by niner** [comment]
No, rakudo won't find the precomp file this way. The only way to load it would be to `require` with a path instead of a module name. Better to just assume implicit precompilation like all the other tests do. Fixed with commit ad4aef0102e3d7dc2e986bf225c4cd93c301d629
