### ISSUE TITLE
integration/advent2011-day23.t fails on Rakudo Star  with 2018.04

### ISSUE THREAD

**Issue by stmuk** [perl6/roast#420]
not ok 33 - for $*ARGFILES.lines {...}
not ok 34 - for lines() {...}

in integration/advent2011-day23.t

**Comment by zoffixznet** [comment]
Can you run it with `t/fudgeandrun t/spec/integration/advent2011-day23.t` and paste the full output that shows how the tests fail?

**Comment by stmuk** [comment]
This is a Rakudo Star issue with running the test not related to OS. It's just not finding the test file README.md. I can reproduce on Linux.  It's just some assumption in the test of how the test is run.

**Comment by Kaiepi** [comment]
This doesn't occur for me testing with a fresh Rakudo build on FreeBSD 11.1.

**Comment by stmuk** [comment]
The test file README.md is absent from 6.c-errata (which is used by Rakudo Star) and should be added.

**Comment by AlexDaniel** [comment]
IMO the test should be changed to not read from `README.md`, just create a temp file, write some data to it and then read it. There's a [`make-temp-file` helper routine](https://github.com/perl6/roast/blob/ab8c502ceb5d81e30edeef7a4556303fe81062f2/packages/Test/Util.pm#L314-L321) to make that easier.
