### ISSUE TITLE
Testing both values of `is-win`

### ISSUE THREAD

**Issue by JJ** [perl6/roast#460]
Such as `roast` is organized now, it will test one code or a different one depending on the value of `$*DISTRO.is-win`. Or said in another way, it's going to need two different machines for testing all code, one with and another without windows.
Adding to that, there's some code that is internally organized independently of the value of that variable. For instance, the one that has caused [this question in SO](https://stackoverflow.com/questions/51732545/changing-a-class-variable-from-outside-the-class). Maybe the way to go is to avoid that kind of code (but that's not an issue related to this repo), but anyway, I think that we should try and use [this hack](https://stackoverflow.com/questions/51731999/changing-distro-values-for-testing) to assign the two possible values to `$*DISTRO` and rewrite all tests so that they check, independently, the two branches of that decision.

**Comment by zoffixznet** [comment]
Which tests in particular are we talking about?

I looked through all the usages that currently exist and all of them are either for choosing right shell syntax, to skip features unsupported on Windows, and a couple of IO::Path tests that choose IO::Path subclass that's different from OS's default.

Which tests actually need the treatment you describe?

**Comment by JJ** [comment]
That is actually right, looks about right. Closing issue.
