### ISSUE TITLE
Rename module suffixes from  .pm to .pm6

### ISSUE THREAD

**Issue by tbrowder** [perl6/roast#464]

**Comment by Altai-man** [comment]
I am :+1: considering style implications, but keep in mind that it'll ruin github's file history feature, which is very neat when you need to find where, why and by who some changes were made.
It still can be traced locally, of course, but might be not so handy sometimes as web interface.
Moving "virtually"(for web-view) erases file history and new starting point will be moving commit, which is LTA, so we may want to consider it.

**Comment by JJ** [comment]
Doing git mv preserves history; the ony thing is that whoever does the
history shows up as "original author". Still, all the commits are there and
show up with "blame"

**Comment by nxadm** [comment]
@JJ That sound good enough.

**Comment by tbrowder** [comment]
I’ll take the action but it will be awhile before I can get to it. I’ll not self-assign yet.

**Comment by tbrowder** [comment]
Closed with merge commit 4d6918a.
