### ISSUE TITLE
CArray is not tested

### ISSUE THREAD

**Issue by JJ** [perl6/roast#478]
They have been implemented in Rakudo, and are tested there, and they are part of the [synopsis](https://design.perl6.org/S21.html#The_CArray_class)
Is it a NYI issue, or is it a design decision?

**Comment by jnthn** [comment]
It's part of `NativeCall`, which I believe we've so far stuck to considering provided with Rakudo rather than being part of the language spec.

**Comment by JJ** [comment]
OK, I see. Thanks.
