### ISSUE TITLE
comb with `Int:D` matcher is not tested

### ISSUE THREAD

**Issue by JJ** [perl6/roast#494]
And it has unexpected behavior, as indicated in rakudo/rakudo#2470

**Comment by zoffixznet** [comment]
Looks to be tested https://github.com/perl6/roast/blob/6.c-errata/S32-str/comb.t#L144-L154

**Comment by JJ** [comment]
OK. So that first number actually corresponds to size, but it's called "matcher" here https://github.com/rakudo/rakudo/blob/de4e82259be36ac9c97b56d594591ea796a1b131/src/core/Cool.pm6#L340

**Comment by zoffixznet** [comment]
Seems to just follow the earlier pattern with `Str` and `Regex` matchers. It's called `$size` on the actual method: https://github.com/rakudo/rakudo/blob/b099266938d4f6e3cb879ef4646f8064fe27bc5b/src/core/Str.pm6#L436

Sidenote: what some implementation chooses to call its internal variables has little effect on what the released spec dictates the language behaviour must be.

**Comment by JJ** [comment]
OK, thanks.
