### ISSUE TITLE
VERSION file in 6.d roast

### ISSUE THREAD

**Issue by zoffixznet** [perl6/roast#506]
The 6.d roast release forgot to change the [`VERSION`](https://github.com/perl6/roast/blob/6.d-errata/VERSION) file, and as such it still claims proposals version is being tested.

It needs to be changed to be similar to how [6.c's VERSION file](https://github.com/perl6/roast/blob/6.c-errata/VERSION) is.

**Comment by zoffixznet** [comment]
Related Rakudo Issue: https://github.com/rakudo/rakudo/issues/2557

**Comment by vrurg** [comment]
Closing due to the same reason as rakudo/rakudo#2557. See also perl6/problem-solving#31.
