### ISSUE TITLE
testing negative exponentials

### ISSUE THREAD

**Issue by MARTIMM** [perl6/roast#53]
Reading through s02 section Exponentials, I found a number representation which I tried in perl6.
Result is
```
> :10<1*2**-64>
===SORRY!=== Error while compiling <unknown file>
Malformed radix number
at <unknown file>:1
------> :10<1*2**⏏-64>
    expecting any of:
        number in radix notation
```
It seems not to accept the minus sign. It will accept positive numbers.
This is not tested in 'S02-literals/radix.t lines 183–192'.

Version of perl;
This is perl6 version 2015.01-77-gd320f00 built on MoarVM version 2015.01-21-g4ee4925

**Comment by Mouq** [comment]
Thanks, @MARTIMM, I just submitted this to the Rakudo bug tracker as [#123862](https://rt.perl.org/Ticket/Display.html?id=123862)

**Comment by zoffixznet** [comment]
This has now been added to the test (albeit fudged): https://github.com/perl6/roast/blob/450b91981a31d72edb64f4b0d0e3941a679a9481/S02-literals/radix.t#L134-L136

I think this Issue can be closed now.
