### ISSUE TITLE
named-def( $key => 15 ) Too many positionals passed; expected 0 arguments but got 1

### ISSUE THREAD

**Issue by electricface** [perl6/roast#65]
```perl6
sub named-def(:$def = 5 ){
    say $def 
}

my $key = 'def'
named-def( $key => 15 )
Too many positionals passed; expected 0 arguments but got 1
```

perl6 -v
This is perl6 version 2015.07.1 built on MoarVM version 2015.07

**Comment by vendethiel** [comment]
This is correct. You're passing a Pair to the function call (the dynamic key does that). You can use `|` to pass a hash as named parameters (`fn(|%args)`).
