### ISSUE TITLE
test fails for t/04-nativecall/16-rt125408.t

### ISSUE THREAD

**Issue by MARTIMM** [perl6/roast#69]
Installing rakudo perl6  with moar
```
make test
...
t/04-nativecall/15-rw-args.t ......... ok     
t/04-nativecall/16-rt125408.t ........ Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/1 subtests 
t/04-nativecall/16-rt125729.t ........ ok   
...
```
More verbose (prove6 is an alias)
```
prove6 -v t/04-nativecall/16-rt125408.t 
t/04-nativecall/16-rt125408.t .. Unhandled exception: Missing or wrong version of dependency 'gen/moar/stage2/QRegex.nqp' (from 'src/gen/m-main.nqp')
   at <unknown>:1  (/home/marcel/Software/lib/perl6/share/perl6/runtime/perl6.moarvm:<dependencies+deserialize>:73)
Dubious, test returned 1 (wstat 256, 0x100)
No subtests run 

Test Summary Report
-------------------
t/04-nativecall/16-rt125408.t (Wstat: 256 Tests: 0 Failed: 0)
  Non-zero exit status: 1
  Parse errors: No plan found in TAP output
Files=1, Tests=0,  0 wallclock secs ( 0.03 usr  0.00 sys +  0.02 cusr  0.00 csys =  0.05 CPU)
Result: FAIL
```
Version is
```
./perl6-m -v
This is perl6 version 2015.07.1-182-g5ba44fc built on MoarVM version 2015.07-108-g7e9f29e
```
OS is
```
uname -a
Linux h03-fedora 4.1.5-100.fc21.x86_64 #1 SMP Tue Aug 11 00:24:23 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by FROGGS** [comment]
Hi, your prove6 output hints that you perhaps forgot to 'make install'?
I think I had seen a message about typed CArrays on my box yesterday
running that test file.

Am 01.09.2015 um 10:21 schrieb Marcel Timmerman:

**Comment by jonathanstowe** [comment]
The test however does fail

[jonathan@coriolanus rakudo]$  /home/jonathan/devel/perl6/rakudo/install/bin/perl6 t/04-nativecall/16-rt125408.t 
1..1
not ok 1 - RT#125408 stayed fixed

# Failed test 'RT#125408 stayed fixed'
# at t/04-nativecall/16-rt125408.t line 15
# Wrong kind of access to numeric CArray
# Looks like you failed 1 test of 1

**Comment by MARTIMM** [comment]
Everything was made first. Done it a second time, same result.

**Comment by jonathanstowe** [comment]
Hi,
I actually made the original bug report that the test is for,  it appeared to be fixed so I wrote the test so the RT could be closed.  Unfortunately the bug crept back in again. You can see the whole history in RT.

**Comment by MARTIMM** [comment]
thanks

**Comment by MARTIMM** [comment]
Perl version 2015.09-95-g3970634 built on MoarVM version 2015.09-35-gd15a446 tests well.
